_target_: utils.llm_interface.OpenAIClient

# Using Aliyun Bailian API
# see more models at https://bailian.console.aliyun.com/?tab=model
model: deepseek-v3
temperature: 1.0
api_key: ${oc.env:OPENAI_API_KEY1,null}
base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
